#dht11
sensor:
    platform: dht
    model: DHT11
    pin: GPIO4
    temperatura:
      name: "temperaturaHaad"
      id:"temp"
    humidity:
      name: "humedadHaad"
      id:"hum"
    update_interval: 5s
