esphome:
  name: esp32-iot3
  friendly_name: ESP32_IoT3

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rx2O2B42SLr67qRj74Wv6ayBoNLQ+gM0a9x64Lq2XOo="

ota:
  password: "your_key"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Iot3 Fallback Hotspot"
    password: "your_password"

captive_portal:
sensor:
    platform: dht
    model: DHT11
    pin: GPIO4
    temperature:
      name: "temperaturaHaad"
      id: "temp"
    humidity:
      name: "humedadHaad"
      id: "hum"
    update_interval: 5s

switch:
    platform: gpio
    name: "releHaad"
    pin: GPIO26


light:
  platform: binary
  name: "led_haad"
  output: light_output

output:
  id: light_output
  platform: gpio
  pin: 
    number: GPIO16
    inverted: true


# Example configuration entry
binary_sensor:
    platform: gpio
    pin: GPIO17
    name: "botón_haad"
    device_class: window
    
i2c:
  sda: GPIO21
  scl: GPIO22

display:
  platform: lcd_pcf8574
  dimensions: 16x2
  address: 0x27
  lambda: |-
    it.printf(2, 0, "%.1f", id(temp).state);
    it.printf(2, 1, "%.1f", id(hum).state);
    it.print(0, 0, "T=");
    it.print(0, 1, "H=");

